<h1 style="font-size: 1em;">Narudzbe</h1>
<a href="<?=App::config('url')?>narudzbe/novo">Dodaj nove narudzbe</a>
<ul style="list-style-type: none">
<?php foreach($narudzbe as $narudzba): ?>
    <li>
    <i title="<?php echo $narudzba->placanje ? 'Placeno' : 'Nije placeno';?>" 
        style="font-size: 1.5em; color:
        <?php echo $narudzba->placanje ? 'green' : 'red';?>" 
        class="fas fa-certificate"></i>
        <span style="font-size: 1.5em;">
        <?=$narudzba->naziv?> 
        </span>
        <a href="<?=App::config('url')?>narudzbe/promjena?sifra=<?=$narudzba->sifra?>">
        <i title="promjena" class="fas fa-2x fa-pencil-alt"></i>
        </a>
        <?php if($narudzba->ukupnoordinacija==0): ?>
            <a href="<?=App::config('url')?>narudzba/brisanje?sifra=<?=$narudzba->sifra?>"
            onclick="return confirm('Sigurno obrisati <?=$narudzba->naziv?>?');">
            <i title="brisanje" style="color: red" class="fas fa-trash-alt"></i></a>
        <?php endif;?>
    </li>
<?php endforeach; ?>
</ul>