<form class="log-in-form" 
    action="<?=App::config('url')?>narudzbe/promjena"
    method="POST">
  <h4 class="text-center">Promjena postojeće narudzbe</h4>
  <label>Naziv
    <input type="text" name="naziv" value="<?=$narudzbe->naziv?>">
  </label>


  <div class="grid-x grid-padding-x">
  <div class="cell large-4">
  <label>Trajanje
    <input type="number" min="1" max="320" name="trajanje" value="<?=$narudzbe->trajanje?>">
  </label>
  </div>
  <div class="cell large-4">
  <label>Datum
    <input type="text" name="datumm" value="<?=$narudzbe->datum?>">
  </label>
  </div>
  <div class="cell large-4">
  <label>Potvrda
        <select name="potvrda">
        <option 
        <?php 
        if($narudzbe->potvrda==='1'){
            echo ' selected="selected" ';
        }
        ?>
         value="1">DA</option>


        <option 
        <?php 
        if($narudzbe->potvrda==='0'){
            echo ' selected="selected" ';
        }
        ?>
         value="0">NE</option>
        </select>
  </label>
  </div>
</div>
 
  <?=$poruka?>

<div class="grid-x grid-padding-x">
  <div class="cell small-6 medium-6 large-6">
    <a class="alert button expanded" 
        href="<?=App::config('url')?>narudzbe/index">Nazad</a>
  </div>
  <div class="cell small-6 medium-6 large-6">
    <input type="submit" class="button expanded" value="Promjena"></input>
  </div>
</div>
<input type="hidden" name="sifra" value="<?=$narudzbe->sifra?>">
</form>