<form class="log-in-form" 
    action="<?=App::config('url')?>index/autorizacija"
    method="POST">
  <h4 class="text-center">Autorizacija</h4>
  <label>Email  :admin@outlook.com
    <input type="email" name="email" value="<?=$email?>">
  </label>
  <label>Lozinka : k
    <input type="password" name="lozinka" >
  </label>
 <p><input type="submit" class="button expanded" value="Prijava"></input></p>
<?=$poruka?>
</form>